
input_knwf_folder: "input_KNIME_workflows/paper_workflows" # Folder containing the selected KNIME workflows
output_json_folder: "parsed_json_workflows" # Folder where the parsed KNIME workflows will be saved
output_xmi_folder: "parsed_xmi_workflows" # Folder where the parsed KNIME workflows will be saved

include_contracts: True # Include contracts in the xmi output
workflow_filename: ""
#workflow_filename: "Model data set with metanode.knwf"

export_mapped_nodes_report: True # Export a report with the mapped nodes percentage
