
input_knwf_folder : "input_KNIME_workflows" # Folder containing the selected KNIME workflows
output_json_folder : "parsed_json_workflows" # Folder where the parsed KNIME workflows will be saved
output_xmi_folder : "parsed_xmi_workflows" # Folder where the parsed KNIME workflows will be saved
